---
debug: on

slack:
  url: 'https://hooks.slack.com/services/111'
  username: 'cdn'
  channel: 'some-channel'
  alwaysFallbackSend: yes

route53:
  zoneId: '123'
  recordName: 'qwerty.com.'

cdnHosts:
  - 'u-01.cdn.qwerty.com'
  - 'u-02.cdn.qwerty.com'
  - 'e-01.cdn.qwerty.com'
  - 'j-01.cdn.qwerty.com'

#
# aws route53 list-traffic-policies
#
policyBasedNormal:
    trafficPolicyId: '2d912bec-8e77-44de-8183-070f5227b302'
    trafficPolicyVersion: 1
    ttl: 60
policyBasedFallback:
    trafficPolicyId: 'ca7be789-cd5f-45af-9e86-310091df7f93'
    trafficPolicyVersion: 1
    ttl: 60

normal:
  - identifier: 'default-content'
    values:
      - '1.2.3.4'
      - '1.1.1.1'
    type: 'A'
    ttl: 60
    countryCode: '*'

  - identifier: 'u-content'
    values:
      - '127.0.0.1'
      - '127.0.0.2'
    type: 'A'
    ttl: 60
    countryCode: 'NA'

  - identifier: 'j-content'
    values:
      - '8.8.8.8'
    type: 'A'
    ttl: 60
    countryCode: 'JP'

  - identifier: 'a-content'
    values:
      - '4.4.4.4'
    type: 'A'
    ttl: 60
    countryCode: 'AS'

  - identifier: 'e-content'
    values:
      - '5.5.5.5'
    type: 'A'
    ttl: 60
    countryCode: 'EU'

fallback:
  - values:
      - 'xxxx.cloudfront.net'
    type: 'CNAME'
    ttl: 60

checks:
  - name: 'ssl'
    domains:
      - 'content.qwerty.com'
      - '*.qwerty.com'
      - 'jp-01.cdn.qwerty.com'
    host: 'jp-01.cdn.qwerty.com'
    port: 443
    timeout: 10

  - name: 'url'
    schema: 'http'
    host: 'j-01.cdn.qwerty.com'
    path: 'checks/status.txt'
    code: 200
    port: 80
    timeout: 10

  - name: 'url'
    schema: 'https'
    host: 'j-01.cdn.qwerty.com'
    path: 'checks/status.txt'
    code: 200
    port: 443
    timeout: 10